### ISSUE TITLE
the module itself has some errors,which i find difficult to rectify.would anyone please help with the erroro

### ISSUE THREAD

**Issue by atul46** [hey-athena/hey-athena-client#34]
![capture](https://cloud.githubusercontent.com/assets/15249435/13603205/844bddf6-e561-11e5-85d4-25a6136c9c8c.PNG)
please we are in dire need of this module..please we need help

**Comment by rcbyron** [comment]
Based on the error traceback, it looks like you just need to upgrade PyAudio to version 0.2.9. This can be done in a lot of different ways depending on your OS. If you used "pip" just try: pip install --upgrade pyaudio

**Comment by atul46** [comment]
no changes even after the update . what would be the real problem here.
![capture](https://cloud.githubusercontent.com/assets/15249435/13624820/78ee7092-e5d7-11e5-9224-36fceeafe12b.PNG)
![capture1](https://cloud.githubusercontent.com/assets/15249435/13624822/7a51df8c-e5d7-11e5-9a4f-47de50173914.PNG)

**Comment by rcbyron** [comment]
It looks like you have both Python 2 and Python 3 installed. "Hey Athena" only works on Python 3. It appears the "pip install --upgrade pyaudio" only upgraded the Python 2 module. Using "pip3" instead of "pip" will fix that (e.g. - "pip3 install --upgrade pyaudio").

The "ALSA" messages are generally just info messages (not errors). However, it might be safe to test the microphone separately. To do this, run the "mic_test.py" file located at "... (python 3 directory)/site-packages/athena/tests/mic_test.py"

Also: When it prompts "Would you like to see the error message?" please type "yes" so that I can see the traceback.

**Comment by atul46** [comment]
will try it for sure and i will let you know the result.thanks BTW
